/* Fixed world coordinates are shared by geometry, drawing and hit testing. */
"use strict";
(() => {
  const tiles = [
  ["Olavi's Wake", "OlavisWakeHex", 0, 4],
  ["Pari Peak", "PariPeakHex", 1, 3],
  ["Palantine Berm", "PalantineBermHex", 1, 5],
  ["The Oarbreaker Isles", "OarbreakerHex", 1, 7],
  ["Kuura Strand", "KuuraStrandHex", 2, 2],
  ["The Gutter", "GutterHex", 2, 4],
  ["Fisherman's Row", "FishermansRowHex", 2, 6],
  ["Stema Landing", "StemaLandingHex", 2, 8],
  ["Nevish Line", "NevishLineHex", 3, 3],
  ["Farranac Coast", "FarranacCoastHex", 3, 5],
  ["Westgate", "WestgateHex", 3, 7],
  ["Origin", "OriginHex", 3, 9],
  ["Callum's Cape", "CallumsCapeHex", 4, 2],
  ["Stonecradle", "StonecradleHex", 4, 4],
  ["King's Cage", "KingsCageHex", 4, 6],
  ["Sableport", "SableportHex", 4, 8],
  ["Ash Fields", "AshFieldsHex", 4, 10],
  ["Speaking Woods", "SpeakingWoodsHex", 5, 1],
  ["The Moors", "MooringCountyHex", 5, 3],
  ["The Linn of Mercy", "LinnMercyHex", 5, 5],
  ["Loch Mór", "LochMorHex", 5, 7],
  ["The Heartlands", "HeartlandsHex", 5, 9],
  ["Red River", "RedRiverHex", 5, 11],
  ["Basin Sionnach", "BasinSionnachHex", 6, 0],
  ["Reaching Trail", "ReachingTrailHex", 6, 2],
  ["Callahan's Passage", "CallahansPassageHex", 6, 4],
  ["Deadlands", "DeadLandsHex", 6, 6],
  ["Umbral Wildwood", "UmbralWildwoodHex", 6, 8],
  ["Great March", "GreatMarchHex", 6, 10],
  ["Kalokai", "KalokaiHex", 6, 12],
  ["Howl County", "HowlCountyHex", 7, 1],
  ["Viper Pit", "ViperPitHex", 7, 3],
  ["Marban Hollow", "MarbanHollow", 7, 5],
  ["The Drowned Vale", "DrownedValeHex", 7, 7],
  ["Shackled Chasm", "ShackledChasmHex", 7, 9],
  ["Acrithia", "AcrithiaHex", 7, 11],
  ["Clanshead Valley", "ClansheadValleyHex", 8, 2],
  ["Weathered Expanse", "WeatheredExpanseHex", 8, 4],
  ["The Clahstra", "ClahstraHex", 8, 6],
  ["Allod's Bight", "AllodsBightHex", 8, 8],
  ["Terminus", "TerminusHex", 8, 10],
  ["Morgen's Crossing", "MorgensCrossingHex", 9, 3],
  ["Stlican Shelf", "StlicanShelfHex", 9, 5],
  ["Endless Shore", "EndlessShoreHex", 9, 7],
  ["Reaver's Pass", "ReaversPassHex", 9, 9],
  ["Godcrofts", "GodcroftsHex", 10, 4],
  ["Tempest Island", "TempestIslandHex", 10, 6],
  ["Wresta", "WrestaHex", 10, 8],
  ["Ónyx", "OnyxHex", 10, 10],
  ["Lykos Isle", "LykosIsleHex", 11, 5],
  ["The Fingers", "TheFingersHex", 11, 7],
  ["Tyrant Foothills", "TyrantFoothillsHex", 11, 9],
  ["Piper's Enclave", "PipersEnclaveHex", 12, 8]
].map(([name, mapName, col, row]) => {
    const x = 512 + col * 768, y = 444 + row * 444;
    return { name, mapName, x, y, bounds: { x: x - 514, y: y - 446, width: 1028, height: 892 },
      polygon: [{x:x-514,y}, {x:x-256,y:y-446}, {x:x+256,y:y-446},
        {x:x+514,y}, {x:x+256,y:y+446}, {x:x-256,y:y+446}] };
  });
  window.OpenWarMap.layout = { tiles, width: 10242, height: 6218,
    byName: new Map(tiles.map(tile => [tile.mapName, tile])) };
})();
